### ISSUE TITLE
jupyterlab-lsp 3.0.0rc0 plan

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/jupyter-lsp-feedstock#7]
Over on https://github.com/krassowski/jupyterlab-lsp/pull/452 @krassowski, (building on @martinrenou's https://github.com/krassowski/jupyterlab-lsp/pull/402) is _soooo_ close :ok_hand: to having a family of [release](https://pypi.org/project/jupyterlab-lsp/3.0.0rc0/) ~~[candidates](https://pypi.org/project/jupyter-lsp/1.0.0rc0/)~~ ready that works with [JupyterLab 3](https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb) :tada:, but we don't want to break peoples' stuff just yet. 

Here are some thoughts on how we move forward... I hope to get this done (later) today, but wanted to write down some stuff as I was researching.

## rc label
Let's do an [rc release](https://github.com/conda-forge/cfep/blob/master/cfep-05.md), as we've done a few upstream dev releases, and this one is more complicated.

I'm thinking our `conda_build_config.yml` will be like:

```yaml
channel_sources:
- conda-forge/label/jupyterlab_rc,conda-forge/label/jupyterlab_server_rc,conda-forge

channel_targets:
- conda-forge jupyter_lsp_rc
```

This will let us easily adapt to upstreams.

## packages
`jupyter-lsp` will get a `1.0.0rc0` release which replaces `notebook` with `jupyter_server`, but is otherwise unchanged.

We'll need a new package, `jupyterlab-lsp 3.0.0rc0` to require `jupyterlab >=3,<4` and `jupyter-lsp >=1.0.0rc0,<2`. We'll have to update this when the real `3.0.0` comes out.
Luckily it's also a straight pip build, `noarch: python`, so no funny stuff there.

I don't know whether we'll want to change the `outputs` for the extra language server stuff, e.g. `jupyterlab-lsp-python`, etc. I'm leaning towards _not_, so we don't have two packages running around, and there's really no relationship between version of `jupyterlab` and the language servers.

## versioning

We'll probably want the "magic" `{{ version }}` to be the `jupyterlab-lsp` one, as it gets released more frequently, no reason not to let the bot do some of the heavy lifting.

**Comment by krassowski** [comment]
One potential change to upstream could be modification of [`install.json`](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#packaging-information) file. The main repo could provide test "pip uninstall jupyterlab-lsp" while here it could be "conda uninstall jupyterlab-lsp".

**Comment by bollwyvl** [comment]
Well, rcs are up, and it _kinda_ works on binder:

https://mybinder.org/v2/gist/bollwyvl/76a720a27be20aec815d171227dc28cd/HEAD?urlpath=lab%2Ftree%2Fenvironment.yml

We probably won't get bot PRs, but it'll be relatively easy to update. We can put some more jinja stuff back in when we (hand) migrate these changes over to `master`.
